export enum Card {
  MIRROR = "MIRROR",
  SKELLIES = "SKELLIES",
  FIRESPIRIT = "FIRESPIRIT",
  ELECTROSPIRIT = "ELECTROSPIRIT",
  ICESPIRIT = "ICESPIRIT",
  HEALSPIRIT = "HEALSPIRIT",
  GOBS = "GOBS",
  SPEARGOBS = "SPEARGOBS",
  ZAP = "ZAP",
  LOG = "LOG",
  BATS = "BATS",
  BOMBER = "BOMBER",
  SNOWBALL = "SNOWBALL",
  BARBBARREL = "BARBBARREL",
  BERSERKER = "BERSERKER",
  ICEGOLEM = "ICEGOLEM",
  WALLBREAKERS = "WALLBREAKERS",
  SUSPICIOUSBUSH = "SUSPICIOUSBUSH",
  RAGE = "RAGE",
  GoblinCurse = "GoblinCurse",
  KNIGHT = "KNIGHT",
  MM = "MM",
  MP = "MP",
  RG = "RG",
  THREEMUSK = "THREEMUSK",
  ARCHERS = "ARCHERS",
  MINIONS = "MINIONS",
  ARROWS = "ARROWS",
  TOMBSTONE = "TOMBSTONE",
  CANNON = "CANNON",
  DARTGOB = "DARTGOB",
  SKARMY = "SKARMY",
  GUARDS = "GUARDS",
  BARREL = "BARREL",
  VINES = "VINES",
  GOBGANG = "GOBGANG",
  SKELLYBARREL = "SKELLYBARREL",
  PRINCESS = "PRINCESS",
  MINER = "MINER",
  FIRECRACKER = "FIRECRACKER",
  EARTHQUAKE = "EARTHQUAKE",
  ICEWIZ = "ICEWIZ",
  GHOST = "GHOST",
  BANDIT = "BANDIT",
  ROYALDELIVERY = "ROYALDELIVERY",
  ELIXIRGOLEM = "ELIXIRGOLEM",
  TORNADO = "TORNADO",
  CLONE = "CLONE",
  VOID = "VOID",
  FISHERMAN = "FISHERMAN",
  LITTLEPRINCE = "LITTLEPRINCE",
  GOBHUT = "GOBHUT",
  GOBLINCAGE = "GOBLINCAGE",
  FIREBALL = "FIREBALL",
  VALK = "VALK",
  RAM = "RAM",
  SKELETONDRAGONS = "SKELETONDRAGONS",
  BOMBTOWER = "BOMBTOWER",
  MORTAR = "MORTAR",
  HOG = "HOG",
  FLYINGMACHINE = "FLYINGMACHINE",
  MUSK = "MUSK",
  BABYD = "BABYD",
  DARKPRINCE = "DARKPRINCE",
  BATTLEHEALER = "BATTLEHEALER",
  FREEZE = "FREEZE",
  RUNEGIANT = "RUNEGIANT",
  POISON = "POISON",
  TESLA = "TESLA",
  ZAPPIES = "ZAPPIES",
  FURNACE = "FURNACE",
  HUNTER = "HUNTER",
  INFERNOD = "INFERNOD",
  EWIZ = "EWIZ",
  GOBLINDEMOLISHER = "GOBLINDEMOLISHER",
  PHOENIX = "PHOENIX",
  MAGICARCHER = "MAGICARCHER",
  GOBLINDRILL = "GOBLINDRILL",
  LUMBER = "LUMBER",
  NIGHTWITCH = "NIGHTWITCH",
  MOTHERWITCH = "MOTHERWITCH",
  GOLDENKNIGHT = "GOLDENKNIGHT",
  SKELETONKING = "SKELETONKING",
  MIGHTYMINER = "MIGHTYMINER",
  WITCH = "WITCH",
  BARBS = "BARBS",
  WIZ = "WIZ",
  INFERNO = "INFERNO",
  ROYALHOGS = "ROYALHOGS",
  BALLOON = "BALLOON",
  PRINCE = "PRINCE",
  HORDE = "HORDE",
  RAMRIDER = "RAMRIDER",
  EDRAGON = "EDRAGON",
  GRAVEYARD = "GRAVEYARD",
  GOBLINMACHINE = "GOBLINMACHINE",
  ARCHERQUEEN = "ARCHERQUEEN",
  RASCALS = "RASCALS",
  GIANT = "GIANT",
  BOWLER = "BOWLER",
  EXE = "EXE",
  GOBLINSTEIN = "GOBLINSTEIN",
  CANNONCART = "CANNONCART",
  MONK = "MONK",
  ROCKET = "ROCKET",
  GIANTSKELLY = "GIANTSKELLY",
  LIGHTNING = "LIGHTNING",
  BARBHUT = "BARBHUT",
  GOBGIANT = "GOBGIANT",
  EBARBS = "EBARBS",
  XBOW = "XBOW",
  SPARKY = "SPARKY",
  PUMP = "PUMP",
  SPIRITEMPRESS = "SPIRITEMPRESS",
  BOSSBANDIT = "BOSSBANDIT",
  PEKKA = "PEKKA",
  ROYALRECRUITS = "ROYALRECRUITS",
  MEGAKNIGHT = "MEGAKNIGHT",
  ELECTROGIANT = "ELECTROGIANT",
  LAVA = "LAVA",
  GOLEM = "GOLEM",
}
export const CardMap: Record<string, string> = {
  [Card.MIRROR]: "Mirror",
  [Card.SKELLIES]: "Skellies",
  [Card.FIRESPIRIT]: "FireSpirit",
  [Card.ELECTROSPIRIT]: "ElectroSpirit",
  [Card.ICESPIRIT]: "IceSpirit",
  [Card.HEALSPIRIT]: "HealSpirit",
  [Card.GOBS]: "Gobs",
  [Card.SPEARGOBS]: "SpearGobs",
  [Card.ZAP]: "Zap",
  [Card.LOG]: "Log",
  [Card.BATS]: "Bats",
  [Card.BOMBER]: "Bomber",
  [Card.SNOWBALL]: "Snowball",
  [Card.BARBBARREL]: "BarbBarrel",
  [Card.BERSERKER]: "Berserker",
  [Card.ICEGOLEM]: "IceGolem",
  [Card.WALLBREAKERS]: "WallBreakers",
  [Card.SUSPICIOUSBUSH]: "SuspiciousBush",
  [Card.RAGE]: "Rage",
  [Card.GoblinCurse]: "GoblinCurse",
  [Card.KNIGHT]: "Knight",
  [Card.MM]: "MM",
  [Card.MP]: "MP",
  [Card.RG]: "RG",
  [Card.THREEMUSK]: "3M",
  [Card.ARCHERS]: "Archers",
  [Card.MINIONS]: "Minions",
  [Card.ARROWS]: "Arrows",
  [Card.TOMBSTONE]: "Tombstone",
  [Card.CANNON]: "Cannon",
  [Card.DARTGOB]: "DartGob",
  [Card.SKARMY]: "Skarmy",
  [Card.GUARDS]: "Guards",
  [Card.BARREL]: "Barrel",
  [Card.VINES]: "Vines",
  [Card.GOBGANG]: "GobGang",
  [Card.SKELLYBARREL]: "SkellyBarrel",
  [Card.PRINCESS]: "Princess",
  [Card.MINER]: "Miner",
  [Card.FIRECRACKER]: "Firecracker",
  [Card.EARTHQUAKE]: "Earthquake",
  [Card.ICEWIZ]: "IceWiz",
  [Card.GHOST]: "Ghost",
  [Card.BANDIT]: "Bandit",
  [Card.ROYALDELIVERY]: "RoyalDelivery",
  [Card.ELIXIRGOLEM]: "ElixirGolem",
  [Card.TORNADO]: "Tornado",
  [Card.CLONE]: "Clone",
  [Card.VOID]: "Void",
  [Card.FISHERMAN]: "Fisherman",
  [Card.LITTLEPRINCE]: "LittlePrince",
  [Card.GOBHUT]: "GobHut",
  [Card.GOBLINCAGE]: "GoblinCage",
  [Card.FIREBALL]: "Fireball",
  [Card.VALK]: "Valk",
  [Card.RAM]: "Ram",
  [Card.SKELETONDRAGONS]: "SkeletonDragons",
  [Card.BOMBTOWER]: "BombTower",
  [Card.MORTAR]: "Mortar",
  [Card.HOG]: "Hog",
  [Card.FLYINGMACHINE]: "FlyingMachine",
  [Card.MUSK]: "Musk",
  [Card.BABYD]: "BabyD",
  [Card.DARKPRINCE]: "DarkPrince",
  [Card.BATTLEHEALER]: "BattleHealer",
  [Card.FREEZE]: "Freeze",
  [Card.RUNEGIANT]: "RuneGiant",
  [Card.POISON]: "Poison",
  [Card.TESLA]: "Tesla",
  [Card.ZAPPIES]: "Zappies",
  [Card.FURNACE]: "Furnace",
  [Card.HUNTER]: "Hunter",
  [Card.INFERNOD]: "InfernoD",
  [Card.EWIZ]: "eWiz",
  [Card.GOBLINDEMOLISHER]: "GoblinDemolisher",
  [Card.PHOENIX]: "Phoenix",
  [Card.MAGICARCHER]: "MagicArcher",
  [Card.GOBLINDRILL]: "GoblinDrill",
  [Card.LUMBER]: "Lumber",
  [Card.NIGHTWITCH]: "NightWitch",
  [Card.MOTHERWITCH]: "MotherWitch",
  [Card.GOLDENKNIGHT]: "GoldenKnight",
  [Card.SKELETONKING]: "SkeletonKing",
  [Card.MIGHTYMINER]: "MightyMiner",
  [Card.WITCH]: "Witch",
  [Card.BARBS]: "Barbs",
  [Card.WIZ]: "Wiz",
  [Card.INFERNO]: "Inferno",
  [Card.ROYALHOGS]: "RoyalHogs",
  [Card.BALLOON]: "Balloon",
  [Card.PRINCE]: "Prince",
  [Card.HORDE]: "Horde",
  [Card.RAMRIDER]: "RamRider",
  [Card.EDRAGON]: "eDragon",
  [Card.GRAVEYARD]: "Graveyard",
  [Card.GOBLINMACHINE]: "GoblinMachine",
  [Card.ARCHERQUEEN]: "ArcherQueen",
  [Card.RASCALS]: "Rascals",
  [Card.GIANT]: "Giant",
  [Card.BOWLER]: "Bowler",
  [Card.EXE]: "Exe",
  [Card.GOBLINSTEIN]: "Goblinstein",
  [Card.CANNONCART]: "CannonCart",
  [Card.MONK]: "Monk",
  [Card.ROCKET]: "Rocket",
  [Card.GIANTSKELLY]: "GiantSkelly",
  [Card.LIGHTNING]: "Lightning",
  [Card.BARBHUT]: "BarbHut",
  [Card.GOBGIANT]: "GobGiant",
  [Card.EBARBS]: "eBarbs",
  [Card.XBOW]: "XBow",
  [Card.SPARKY]: "Sparky",
  [Card.PUMP]: "Pump",
  [Card.SPIRITEMPRESS]: "SpiritEmpress",
  [Card.BOSSBANDIT]: "BossBandit",
  [Card.PEKKA]: "PEKKA",
  [Card.ROYALRECRUITS]: "RoyalRecruits",
  [Card.MEGAKNIGHT]: "MegaKnight",
  [Card.ELECTROGIANT]: "ElectroGiant",
  [Card.LAVA]: "Lava",
  [Card.GOLEM]: "Golem",

};

export const CardMapToPortuguese: Record<string, string> = {
  [Card.MIRROR]: "Espelho",
  [Card.SKELLIES]: "Esqueletos",
  [Card.FIRESPIRIT]: "Espírito de Fogo",
  [Card.ELECTROSPIRIT]: "Espírito Elétrico",
  [Card.ICESPIRIT]: "Espírito de Gelo",
  [Card.HEALSPIRIT]: "Espírito Curandeiro",
  [Card.GOBS]: "Goblins",
  [Card.SPEARGOBS]: "Goblins lanceiros",
  [Card.ZAP]: "Zap",
  [Card.LOG]: "Tronco",
  [Card.BATS]: "Morcegos",
  [Card.BOMBER]: "Bombardeiro",
  [Card.SNOWBALL]: "Bola de Neve",
  [Card.BARBBARREL]: "Barril de Bárbaros",
  [Card.BERSERKER]: "Berserker",
  [Card.ICEGOLEM]: "Golem de Gelo",
  [Card.WALLBREAKERS]: "Destruidores de Muros",
  [Card.SUSPICIOUSBUSH]: "Arbustos Traiçoeiros",
  [Card.RAGE]: "Fúria",
  [Card.GoblinCurse]: "Maldição Goblin",
  [Card.KNIGHT]: "Cavaleiro",
  [Card.MM]: "Megasservo",
  [Card.MP]: "Mini P.E.K.K.A",
  [Card.RG]: "Gigante Real",
  [Card.THREEMUSK]: "Três Mosqueteiras",
  [Card.ARCHERS]: "Arqueiras",
  [Card.MINIONS]: "Servos",
  [Card.ARROWS]: "Flechas",
  [Card.TOMBSTONE]: "Lápide",
  [Card.CANNON]: "Canhão",
  [Card.DARTGOB]: "Goblin com Dardo",
  [Card.SKARMY]: "Exército de Esqueletos",
  [Card.GUARDS]: "Guardas",
  [Card.BARREL]: "Barril de Goblins",
  [Card.VINES]: "Vinhas",
  [Card.GOBGANG]: "Gangue de Goblins",
  [Card.SKELLYBARREL]: "Barril de Esqueletos",
  [Card.PRINCESS]: "Princesa",
  [Card.MINER]: "Mineiro",
  [Card.FIRECRACKER]: "Pirotécnica",
  [Card.EARTHQUAKE]: "Terremoto",
  [Card.ICEWIZ]: "Mago de Gelo",
  [Card.GHOST]: "Fantasma Real",
  [Card.BANDIT]: "Bandida",
  [Card.ROYALDELIVERY]: "Encomenda Real",
  [Card.ELIXIRGOLEM]: "Golem de Elixir",
  [Card.TORNADO]: "Tornado",
  [Card.CLONE]: "Clone",
  [Card.VOID]: "Vácuo",
  [Card.FISHERMAN]: "Pescador",
  [Card.LITTLEPRINCE]: "Pequeno Príncipe",
  [Card.GOBHUT]: "Cabana de Goblins",
  [Card.GOBLINCAGE]: "Jaula de Goblin",
  [Card.FIREBALL]: "Bola de Fogo",
  [Card.VALK]: "Valquíria",
  [Card.RAM]: "Aríete de Batalha",
  [Card.SKELETONDRAGONS]: "Dragões Esqueletos",
  [Card.BOMBTOWER]: "Torre de Bombas",
  [Card.MORTAR]: "Morteiro",
  [Card.HOG]: "Corredor",
  [Card.FLYINGMACHINE]: "Máquina Voadora",
  [Card.MUSK]: "Mosqueteira",
  [Card.BABYD]: "Bebê Dragão",
  [Card.DARKPRINCE]: "Príncipe das Trevas",
  [Card.BATTLEHEALER]: "Curandeira Guerreira",
  [Card.FREEZE]: "Gelo",
  [Card.RUNEGIANT]: "Gigante das Runas",
  [Card.POISON]: "Veneno",
  [Card.TESLA]: "Tesla",
  [Card.ZAPPIES]: "Eletrocutadores",
  [Card.FURNACE]: "Fornalha",
  [Card.HUNTER]: "Caçador",
  [Card.INFERNOD]: "Dragão Infernal",
  [Card.EWIZ]: "Mago Elétrico",
  [Card.GOBLINDEMOLISHER]: "Goblin Demolidor",
  [Card.PHOENIX]: "Fênix",
  [Card.MAGICARCHER]: "Arqueiro Mágico",
  [Card.GOBLINDRILL]: "Escavadeira de Goblins",
  [Card.LUMBER]: "Lenhador",
  [Card.NIGHTWITCH]: "Bruxa Sombria",
  [Card.MOTHERWITCH]: "Bruxa Mãe",
  [Card.GOLDENKNIGHT]: "Cavaleiro Dourado",
  [Card.SKELETONKING]: "Rei Esqueleto",
  [Card.MIGHTYMINER]: "Mineiro Bombado",
  [Card.WITCH]: "Bruxa",
  [Card.BARBS]: "Bárbaros",
  [Card.WIZ]: "Mago",
  [Card.INFERNO]: "Torre Inferno",
  [Card.ROYALHOGS]: "Porcos Reais",
  [Card.BALLOON]: "Balão",
  [Card.PRINCE]: "Príncipe",
  [Card.HORDE]: "Horda de Servos",
  [Card.RAMRIDER]: "Domadora de Carneiro",
  [Card.EDRAGON]: "Dragão Elétrico",
  [Card.GRAVEYARD]: "Cemitério",
  [Card.GOBLINMACHINE]: "Máquina Goblin",
  [Card.ARCHERQUEEN]: "Rainha Arqueira",
  [Card.RASCALS]: "Patifes",
  [Card.GIANT]: "Gigante",
  [Card.BOWLER]: "Lançador",
  [Card.EXE]: "Executor",
  [Card.GOBLINSTEIN]: "Goblinstein",
  [Card.CANNONCART]: "Carrinho de Canhão",
  [Card.MONK]: "Monge",
  [Card.ROCKET]: "Foguete",
  [Card.GIANTSKELLY]: "Esqueleto Gigante",
  [Card.LIGHTNING]: "Relâmpago",
  [Card.BARBHUT]: "Cabana de Bárbaros",
  [Card.GOBGIANT]: "Goblin Gigante",
  [Card.EBARBS]: "Bárbaros de Elite",
  [Card.XBOW]: "X-Besta",
  [Card.SPARKY]: "Sparky",
  [Card.PUMP]: "Coletor de Elixir",
  [Card.SPIRITEMPRESS]: "Imperatriz Espiritual",
  [Card.BOSSBANDIT]: "Bandida Líder",
  [Card.PEKKA]: "P.E.K.K.A",
  [Card.ROYALRECRUITS]: "Recrutas Reais",
  [Card.MEGAKNIGHT]: "Megacavaleiro",
  [Card.ELECTROGIANT]: "Gigante Elétrico",
  [Card.LAVA]: "Lava Hound",
  [Card.GOLEM]: "Golem",
}
